version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: npm run coverage